title: Damien's Adventure # the title of your blog

subtitle: Enjoy Programming (and even more...) # subtitle of your blog

description: >- # this means to ignore newlines until "baseurl:"
  I share my passion about Computer Science and programming.
  You can find posts about my research, some tutorials in
  programming, or just sharing my knowledge. I particularly use the
  Swift language, created by Apple.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# All the images can be found at - /_site/assets/img/

author_logo: ma_tete.png  # your profile image

# disqus_shortname: your-disqus-username   #for comments using disqus

# Author details

author: Damien Morard
author_bio: >- # this means to ignore newlines until "author_email:"
  Hey ! I'm Damien, a PhD student at the university of Geneva.
  My research field is Computer Science, and my research areas are semantics, modeling and verification.
  I'm working on a way to improve High-level Petri nets, adding a way to use functions as token.
  I want to reduce the semantic gap between model and implementation.

author_email: "damien@morard.me"
author_location: France
author_website_url: "https://morard.me"

# social links
# twitter_username: yourusername
github_username:  damdamo
# facebook_username: yourusername
linkedin_username: damienmorard
# behance_username: yourusername
# instagram_username: yourusername
medium_username: dmorard1
# telegram_username: yourusername
# dribbble_username: yourusername
# flickr_username: yourusername

# important to use devlopr theme
theme: devlopr

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
